services:
  portal:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DHIS2_BASE_PAT_TOKEN: ${DHIS2_BASE_PAT_TOKEN}
        DHIS2_BASE_URL: ${DHIS2_BASE_URL}
        CONTEXT_PATH: ${CONTEXT_PATH}
    user: "1001:1001"
    ports:
      - "${PORTAL_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - public:/app/apps/portal/public
volumes:
  public:
networks:
  default:
    name: portal-network
    driver: bridge
