services:
  portal:
    image: hisptanzania/dhis2-public-portal:latest
    user: "1001:1001"
    ports:
      - "3000:3000"
    environment:
      - DHIS2_BASE_URL=https://your-dhis2-instance.org
      - DHIS2_BASE_PAT_TOKEN=your-personal-access-token
      - CONTEXT_PATH=
    volumes:
      - public:/app/apps/portal/public


volumes:
  public:

