name: TypeScript Type Check

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - '**/tsconfig.json'

jobs:
  type-check:
    name: Run TypeScript Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          DHIS2_BASE_URL: ${{vars.DHIS2_BASE_URL}}
          DHIS2_BASE_PAT_TOKEN: ${{secrets.DHIS2_BASE_PAT_TOKEN}}

      - name: Check types
        run: yarn check-types
